version: '3'
services:
  # stream-frontend:
  #   restart: always
  #   image: melodisticmonorepo_stream-frontend
  #   build: 
  #     context: streaming-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=opalhas1secret
    networks:
      - melodistic-network
  melodistic_stream:
    restart: always
    image: melodisticmonorepo_stream-backend
    build:
      context: stream
      dockerfile: Dockerfile
    volumes:
      - ./combine-result:/app/combine-result
    ports:
      - "5050:5050"
    networks:
      - melodistic-network
  melodistic_combiner:
    restart: always
    image: melodisticmonorepo_combiner-system
    build:
      context: combiner/server
      dockerfile: Dockerfile
    volumes:
      - ./extract-data/song:/app/song
      - ./extract-data/features:/app/features
      - ./combine-result:/app/combine-result
    ports:
      - "5500:5500"
    deploy:
      resources:
        limits:
          memory: 10g
    networks:
      - melodistic-network
  melodistic_backend:
    restart: always
    image: melodisticmonorepo_backend
    depends_on:
      - redis
    build:
      context: Melodistic-Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    links:
      - "redis:melodistic_redis"
    environment:
      - DATABASE_URL=postgresql://melodistic:melodistic-pwd@20.24.21.220:5432/melodistic?schema=public
      - JWT_SECRET=opalhas1secret
      - GOOGLE_CLIENT_ID=237236624261-vjk2fq2s9ns30vccaain77ah758ejh53.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - PORT=3000
      - REDIS_HOST=melodistic_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=opalhas1secret
      - EMAIL_FROM_ADDRESS=melodistic-service@ggolfz.me
      - SENDGRID_API_KEY=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
    networks:
      - melodistic-network
  nginx:
    restart: always
    depends_on:
      - melodistic_stream
      - melodistic_backend
      - melodistic_combiner
    image: melodisticmonorepo_nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    links:
      - "melodistic_backend:melodistic_backend"
      - "melodistic_stream:melodistic_stream"
      - "melodistic_combiner:melodistic_combiner"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - melodistic-network
networks:
  melodistic-network: